name: DYiu
favicon: null
layout_spectrum: 0.11926572653464973
typography_spectrum: 0.44474875763989985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9120926747564226
  lightness: 0.5409648776985705
  saturation: 0.11753737507387996
  rhythmicContrast: 0.6521582591813058
purpose: []
